cart/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)$', views.cart_remove, name="cart_remove")

]

main/urls.py
from . import views
from django.urls import path
from django.urls.conf import include  # Добавить к существующим маршрутов, маршруты нового приложения
from django.conf.urls import url

urlpatterns = [
    path("", views.index, name = "index"),
    url(r'^(?P<category_slug>[-\w]+)/$',
         views.product_list,
         name="product_list_by_category"),
    path("about_us/", views.about),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

site1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("cart/", include(("cart.urls", "cart"), namespace ="cart")),
    path("", include(("main.urls", "main"), namespace = "main")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)       # Строка с симфолами, для названий
    slug = models.SlugField(max_length=200, db_index=True, unique=True)   # Ссылка на категорию транслитом
    image = models.ImageField(upload_to="Engins")                # ИСПРАВИТЬ | Изображения которые которые хратьнсятся в папке
    parent = models.ForeignKey("self", blank=True, null=True, related_name="children", on_delete=models.CASCADE)     # Связь с другими таблицаи из базы | Связываем ключь одной таблицы с другой таблицей
    class Meta:        # Подкласс для оформления(вспомогательный класс), Сортировка
        ordering =("name",)
        verbose_name ="Категория"
        verbose_name_plural = "Категории"
        unique_together =("slug", "parent",)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("main:product_list_by_category", args=[self.slug])



class Engine(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="Engins")
    slug = models.SlugField(max_length=200, db_index=True)
    category = models.ForeignKey(Category, blank=True, null=True, related_name="product", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True)
    product_information = models.TextField(blank=True)
    stock = models.PositiveIntegerField()          # Колличество на складе
    availbale = models.BooleanField(default=True)     # Логическтое поле
    created = models.DateField(auto_now_add=True)     # Поля с датой и временем, когда был товар создан
    updated = models.DateField(auto_now=True)     # Когда был товар отредактирован

    def get_absolute_url(self):
        return reverse("main:product_detail", args=[self.id, self.slug])

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label="Колличество", widget=forms.TextInput(attrs={'id': 'quantityInp', 'value': 1, 'pattern': '[0-9]*'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import redirect, render, get_object_or_404

from .forms import CartAddProductForm
from django.views.decorators.http import require_POST
from main.models import Engine
from .cart import Cart

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    engine = get_object_or_404(Engine, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=engine,
                 quantity=cd['quantity'],
                 update_quantity=cd['update']
                 )
    return redirect('cart:cart_detail')



def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart.html', {'cart': cart})


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Engine, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")

main/views.py
from django.shortcuts import render, get_object_or_404
from django.urls.base import reverse
from .models import Engine, Category
from cart.forms import CartAddProductForm




def index(request):
    engines = Engine.objects.all()
    return render(request, "main/index.html", {"engins": engines})

def about(request):
    return render(request, "main/about.html", {})

def product_list(request, category_slug=None):
    category = None
    categoryes = Category.objects.all()
    engines = Engine.objects.filter(availbale=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        engines = Engine.objects.filter(category=category)
    else:
        engines = engines[:12]
    return render(request, "main/index.html", {"engins": engines, "category": category})

def product_detail(request, id, slug):
    product = Engine.objects.filter(id = id,
                                    slug = slug,
                                    availbale = True
                                    )[0]
    cart_product_form = CartAddProductForm
    return render(request, 'main/product_detale.html', {'engine': product,
                                                 'cart_product_form': cart_product_form})



# """методы, модетей"""

cart/templates/cart/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Корзина</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">

</head>
<body>
    <div class="conteiner">
    <h1>Ваша корзина</h1>
    <div class="cart">
    {% if cart|length == 0 %}
    <div class="cart_empty">
        <h2 class="cart_empty_headline">Корзина пуста</h2>
    </div>
    {% else %}
        <div class="cart_item_list">
        {% for item in cart %}
        {% with product=item.product %}
        <div class="cart_item">
            <div class="cart_item_image">
                <a href="{{ product.get_absolut_url }}">
                <img src="{{product.image.url}}">
                </a>
            </div>

            <div class="cart_item_name">
                {{ product.name}}
            </div>

            <div class="cart_item_quantity">
                {{ item.quantity }} шт.
            </div>

            <div class="cart_item_cost">
                <p>Стоимость: {{ item.total_price }} Рублей</p>
                <p>Цена за штуку: {{ item.price }} Рублей</p>
            </div>

            <a class="cart_item_remove" href="{% url "cart:cart_remove" product.id %}">x</a>

        </div>
        {% endwith %}
        {% endfor %}
    </div>

    <div class="cart_details">
        <div class="cart_total">
            <h5>Сумма: {{ cart.get_total_price }}</h5>
        </div>
        <a href="{% url "main:index" %}" class="cart_shop">Продолжить покупку</a>
        {% comment %} <a href="{% url "orders:order_create" %}" class="cart_order">
            Оформить заказ
        </a> {% endcomment %}
    </div>

    </div>

        </div>
    {% endif %}

    </div>
    </div>
</body>
</html>

main/templates/main/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welkome Spaces<h1>
</body>
</html>

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Roboto+Slab:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>


    <main>
        <div class="categories">
        {% include "main/navbar.html" %}
            <ul class="categories_list">
            {% for category in categories %}
            <li class="category_item"><a class="category_link" href={{category.get_absolute_url}}>{{category.name}}</a></li>
            {% endfor %}
            </ul>
        </div>

    {% block content %}{% endblock content %}
    </main>

    <footer>Сайт для продажи запчастей</footer>

</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="engine_catalog">
    <h1>{% if category %}{{category.name}}{% else %}Каталог{% endif %}:</h1>

    <div class="engine_list">
        {% for engine in engins %}
        <div class="engine">
            <div class="engine_head"><img src="{{engine.image.url}}" alt="{{engine.name}}"></div>
            <div class="engine_boby">
                <h3 class="engine_name">{{engine.name}}</h3>
                <a href={{engine.get_absolute_url}} class="engine_buy_main">Детальнее</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock  %}

main/templates/main/navbar.html
<div class="navbar">
    <a href={% url 'main:index' %} class="engine_detail_button"> Вернуться на главную</a>
</div>

main/templates/main/product_detale.html
{% extends 'main/base.html' %}
{% load static %}

    {% block content %}

    {% comment %} <h1>{{category.name}}</h1> {% endcomment %}

    <div class="engine_detail">
        <div class="engine_detaile_head"><img src="{{engine.image.url}}" alt="{{engine.name}}"></div>
        <div class="engine_detail_boby">
            <h3 class="engine_detail_name">{{engine.name}}</h3>
                <p class="engine_detail_price"> Цена: {{engine.price}}</p>
                <p class="engine_detail_description"> Описание: {{engine.description}}</p>
                <p class="engine_detail_product_information"> Информация: {{engine.product_information}}</p>
                <p class="engine_detail_stock"> {% if engine.stock > 0 %}Товаров на складе: {{engine.stock}} {% else %}Товаров нет на складе {% endif %}</p>

            <form action={% url 'cart:cart_add' engine.id %} method='POST'>
                <div class="quantity">

                {{ cart_product_form.quantity }}

                </div>

                {% csrf_token %}
                <button class="engine_buy" href=>Купить</button>

            </form>
        </div>
    </div>


{% endblock %}